core/urls.py
""" core URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps.sitemaps import *
from .sitemaps.views import *
# sitemaps = {
#     'posts': ArticleSitemap,
#     'products': ProductSitemap,
# }

urlpatterns = [


    path('admin/', admin.site.urls),


    
    path('ckeditor/', include('ckeditor_uploader.urls')),


    # Main urls
    path('', include('main.urls', namespace='main')),

    # Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    # article urls
    path('blog/', include('article.urls', namespace='article')),
    # game urls
    path('game/', include('game.urls')),

]

handler404 = 'main.views.handler404'

# Development
if bool(settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . views import *

app_name = 'dashboard'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('messages/', MessagesView.as_view(), name='messages'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),

]

dashboard/models.py
from django.db import models

dashboard/forms.py
from django import forms
from .models import SellControl


class SellControlForm(forms.ModelForm):
    class Meta:
        model = SellControl
        fields = ('is_open', )

dashboard/views.py
from django.db.models.aggregates import Sum, Count
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from .models import *
from accounts.models import *
from accounts.mixins import *
from django.db.models import Q, Count
from django.http import HttpResponse
from jalali_date import datetime2jalali, date2jalali
from datetime import datetime, timedelta
import csv, xlwt
import pandas as pd
from django.contrib import messages

from main.models import ContactMessage
from site_info.models import SiteInfo


# --------------------------------- Home View ---------------------------------
class HomeView(LoginRequiredMixin, AdminAccessMixin, generic.TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        today = datetime.today().date()
        context = super().get_context_data(**kwargs)
        context["customers_count"] = User.objects.count()

        return context



# --------------------------------messages views--------------------------------------
class MessagesView(LoginRequiredMixin, AdminAccessMixin, generic.ListView):
    model = ContactMessage
    template_name = 'dashboard/messages/messages.html'
    context_object_name = 'contact_messages'
    paginate_by = 50

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'پیام'
        context["object_name_fa_plural"] = 'پیام ها'
        context['objects_count'] = self.get_queryset().count()

        return context
    def get_queryset(self):
        queryset = super().get_queryset()
        search_filter = self.request.GET.get('search', None)
        status_filter = self.request.GET.get('status', None)

        if status_filter:
            if status_filter in dict(ContactMessage.STATUS_CHOICES).keys():
                queryset = queryset.filter(status=status_filter)

        if search_filter:
            queryset = queryset.filter(Q(code__icontains=search_filter))


        return queryset


class MessageDetailView(LoginRequiredMixin, AdminAccessMixin, generic.DetailView):
    model = ContactMessage
    template_name = 'dashboard/messages/message_detail.html'
    context_object_name = 'message'
    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'پیام'
        context["object_name_fa_plural"] = 'پیام ها'

        return context
    def get_object(self):
        obj = super().get_object()
        # Mark as seen if not already seen
        if obj.status == 'not_seen':
            obj.status = 'seen'
            obj.seen_at = timezone.now()
            obj.save()
        return obj


# --------------------------------- Orders View ---------------------------------
class OrderView(LoginRequiredMixin, AdminAccessMixin, generic.ListView):
    model = SiteInfo
    template_name = 'dashboard/site/site.html'
    context_object_name = 'orders'
    paginate_by = 10

    def get_shared_context(self, context):
        context["object_name_fa"] = 'سفارش'
        context["object_name_fa_plural"] = 'سفارشات'

        return context

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'سفارش'
        context["object_name_fa_plural"] = 'سفارشات'
        context['objects_count'] = self.get_queryset().count()
        context['users'] = User.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        user_filter_id = self.request.GET.get('user_filter', None)
        is_paid = self.request.GET.get('is_paid', None)
        status = self.request.GET.get('status', None)
        delivery_option = self.request.GET.get('delivery_option', None)
        search = self.request.GET.get('search', None)

        if user_filter_id and user_filter_id != 'all':
            queryset = queryset.filter(user__id=user_filter_id)

        if is_paid and is_paid != 'None':
            is_paid = is_paid == 'True'
            queryset = queryset.filter(is_paid=is_paid)

        if status and status != 'all':
            queryset = queryset.filter(shipping_status=status)

        if delivery_option and delivery_option != 'all':
            queryset = queryset.filter(delivery_option=delivery_option)

        if search:
            queryset = queryset.filter(Q(code__icontains=search))

        return queryset


class OrderUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = SiteInfo
    fields = ('name', 'logo', 'email', 'phone', 'is_paid',
              'address', 'description', )

    template_name = 'dashboard/site/site.html'
    success_message = 'تغییرات ثبت گردید'

    def get_success_url(self):
        return reverse('dashboard:site')

    def form_valid(self, form):

        return super().form_valid(form)

    def form_invalid(self, form):
        # Add errors to messages
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{form.fields[field].label}: {error}")

        return self.form_invalid_redirect()

    def form_invalid_redirect(self):
        return redirect(reverse('dashboard:site'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_name_fa'] = 'سفارش'
        context['object_name_fa_plural'] = 'سفارشات'
        context['users'] = User.objects.all()

        return context

templates/dashboard/includes/clustering.html
{% extends "dashboard/layouts/base-fullscreen.html" %}

{% block title %} عملیات خوشه‌بندی {% endblock %}

{% block content %}

{% load static %}
<div class="auth-wrapper">
	<div class="auth-content">
		<div class="auth-bg">
			<span class="r"></span>
			<span class="r s"></span>
			<span class="r s"></span>
			<span class="r"></span>
		</div>
		<div class="card rounded shadow p-4">
			<div class="card-body text-center">
				<div class="mb-5 mt-1">
					{% comment %} <i class="feather icon-user auth-icon"></i> {% endcomment %}
					<img src="{{ site.large_logo_dark.url }}" class="mx-auto d-flex" loading="lazy"
						alt="{{ site.title }}"> </div>
				<h3 class="mb-0">عملیات خوشه‌بندی
					<br>
					انجام گردید.</h3>

				<br />

				<span class="text-muted">
					فقط کاربران ادمین به این صفحه دسترسی دارند.
					<br>
					<a href="/">بازگشت به صفحه اصلی</a>
				</span>

				<a href="{% url 'accounts:logout' %}" class="text-danger d-block mt-5 font-weight-normal">
					<i class="feather icon-log-out"></i>
					خروج از سایت
				</a>

			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/dashboard/includes/iran_city_names_map.html
tooltip: {
    pointFormatter: function() {
        if (this['hc-key'] === 'ir-hg') {
            return 'هرمزگان: ' + this.value;
        }

        if (this['hc-key'] === 'ir-bs') {
            return 'بوشهر: ' + this.value;
        }


        if (this['hc-key'] === 'ir-kb') {
            return 'کهگیلویه و بویراحمد: ' + this.value;
        }


        if (this['hc-key'] === 'ir-fa') {
            return 'فارس: ' + this.value;
        }


        if (this['hc-key'] === 'ir-es') {
            return 'اصفهان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-sm') {
            return 'سمنان: ' + this.value;
        }

        if (this['hc-key'] === 'ir-go') {
            return 'گلستان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-mn') {
            return 'مازندران: ' + this.value;
        }


        if (this['hc-key'] === 'ir-th') {
            return 'تهران: ' + this.value;
        }


        if (this['hc-key'] === 'ir-mk') {
            return 'مرکزی: ' + this.value;
        }


        if (this['hc-key'] === 'ir-ya') {
            return 'یزد: ' + this.value;
        }

        if (this['hc-key'] === 'ir-cm') {
            return 'چهارمحال و بختیاری: ' + this.value;
        }


        if (this['hc-key'] === 'ir-kz') {
            return 'خوزستان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-lo') {
            return 'لرستان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-il') {
            return 'ایلام: ' + this.value;
        }


        if (this['hc-key'] === 'ir-ar') {
            return 'اردبیل: ' + this.value;
        }

        if (this['hc-key'] === 'ir-qm') {
            return 'قم: ' + this.value;
        }


        if (this['hc-key'] === 'ir-hd') {
            return 'همدان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-za') {
            return 'زنجان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-qz') {
            return 'قزوین: ' + this.value;
        }


        if (this['hc-key'] === 'ir-wa') {
            return 'آذربایجان غربی: ' + this.value;
        }

        if (this['hc-key'] === 'ir-ea') {
            return 'آذربایجان شرقی: ' + this.value;
        }


        if (this['hc-key'] === 'ir-bk') {
            return 'کرمانشاه: ' + this.value;
        }


        if (this['hc-key'] === 'ir-gi') {
            return 'گیلان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-kd') {
            return 'کردستان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-kj') {
            return 'خراسان جنوبی: ' + this.value;
        }

        if (this['hc-key'] === 'ir-kv') {
            return 'خراسان رضوی: ' + this.value;
        }


        if (this['hc-key'] === 'ir-ks') {
            return 'خراسان شمالی: ' + this.value;
        }


        if (this['hc-key'] === 'ir-sb') {
            return 'زاهدان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-ke') {
            return 'کرمان: ' + this.value;
        }


        if (this['hc-key'] === 'ir-al') {
            return 'البرز: ' + this.value;
        }


        

        return this.name + ' ' + this.value;
    }
},


{% comment %} dataLabels: {
    enabled: false,
    formatter: function() {
        if (this.point['hc-key'] === 'ir-th') {
            return 'hhhhhhh';
        }

        return this.point.name
    }
}, {% endcomment %}

templates/dashboard/includes/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">
	{{ message }}
</div>
{% endfor %}
{% endif %}

templates/dashboard/includes/pagination.html
<nav class='e_custom_pagination' aria-label="Page navigation example">
  {% if is_paginated %}
  <ul class="pagination">

    {% comment %} {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">&laquo;</a>
    </li>
    {% endif %} {% endcomment %}

    {# First page #}
    {% if page_obj.number != 1  %}
     <li class="page-item"><a class="page-link" href="?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{key}}={{value}}{% endif %}{% endfor %}">اولین صفحه</a></li>
    {% endif %}

    {% if page_obj.number|add:'-4' > 1 %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{key}}={{value}}{% endif %}{% endfor %}">&hellip;</a></li>
    {% endif %}


    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item"><a class="page-link active">{{ i }}</a></li>

    {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'10' %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{key}}={{value}}{% endif %}{% endfor %}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{key}}={{value}}{% endif %}{% endfor %}">&hellip;</a></li>
    {% endif %}

      {# Last page #}
      {% if page_obj.number != page_obj.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.paginator.num_pages}}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{key}}={{value}}{% endif %}{% endfor %}">آخرین صفحه</a>
      </li>
     {% endif %}

    {% comment %} {% if page_obj.has_next %}
    <li class="page-item">
      <a href="?page={{page_obj.next_page_number}}" class="page-link">&raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">&raquo;</a>
    </li>
    {% endif %} {% endcomment %}
  </ul>
  {% endif %}
</nav>

templates/dashboard/includes/scripts.html
{% load static %}

<!-- Required Js -->
<script src="{% static 'dashboard/js/vendor-all.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dashboard/js/pcoded.min.js' %}"></script>

<!-- Notification Js -->
<script src="{% static 'dashboard/plugins/notification/bootstrap-growl.min.js' %}"></script>

<!-- Custom Js -->
<script src="{% static 'dashboard/js/custom-js.js' %}"></script>
<script src="{% static 'dashboard/js/custom-full-screen.js' %}"></script>
<script src="{% static 'dashboard/js/download-pdf-image.js' %}"></script>
<script src="{% static 'dashboard/js/top-filter.js' %}"></script>
<script src="{% static 'dashboard/js/side-filter.js' %}"></script>

<!-- data tables -->
<script src="{% static 'dashboard/js/management/datatables.min.js' %}"></script>
<script src="{% static 'dashboard/js/management/tbl-datatable-custom.js' %}"></script>

<!-- jsDeliver -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.min.js"></script>
<script type="text/javascript"
        src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.plugins.min.js"></script>

<!-- select2  for searchabale selectable input -->
<script src="{% static 'dashboard/plugins/select2/select2.full.min.js' %}"></script>

<!-- jalalidatepicker input -->
<script src="{% static 'dashboard/plugins/jalalidatepicker/jalalidatepicker.min.js' %}"></script>

<!-- Load CKEditor from CDN -->
<script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>

<script>
    {% comment %}  messags  {% endcomment %}
    {% if messages %}
        {% for message in messages %}
            function notify(message, type) {
                $.growl({
                    message: message
                }, {
                    type: type,
                    allow_dismiss: false,
                    label: 'Cancel',
                    className: 'btn-xs btn-inverse',
                    placement: {
                        from: 'bottom',
                        align: 'left'
                    },
                    delay: 8000,
                    animate: {
                        enter: 'animated fadeInUp',
                        exit: 'animated fadeOutUp'
                    },
                    offset: {
                        x: 30,
                        y: 30
                    }
                });
            };
            notify('{{ message }}', '{{ message.tags }}');
        {% endfor %}
    {% endif %}


    {% comment %} Side Bar collapse{% endcomment %}
    $('#sidebar').on('click', function () {
        if ($(this).hasClass('navbar-collapsed')) {
            $(this).toggleClass('closed')
            $('.nav-item').removeClass('pcoded-trigger')
            $('.pcoded-submenu').css('display', 'none')
        }

        if ($(this).hasClass('closed')) {
            $('#sidebar_logo').attr('src', '{{site.small_logo_light.url}}');
            $('#sidebar_logo').removeAttr('style');
            $('#sidebar_logo').css({
                "width": "45px"
            });
        } else {
            $('#sidebar_logo').removeAttr('style');
            $('#sidebar_logo').attr('src', '{{site.large_logo_light.url}}');
        }
    })

    $('.pcoded-inner-navbar li.pcoded-hasmenu').on('click', function () {

        $('#sidebar').removeClass('closed')

        if ($(this).hasClass('closed')) {
            $('#sidebar_logo').attr('src', '{{site.small_logo_light.url}}');
            $('#sidebar_logo').removeAttr('style');
            $('#sidebar_logo').css({
                "width": "50px"
            });
        } else {
            $('#sidebar_logo').removeAttr('style');
            $('#sidebar_logo').attr('src', '{{site.large_logo_light.url}}');
        }
    });


    {% comment %} export_download {% endcomment %}
    if ($('#export_download').length) {
        {% comment %} $('#export_download').click(function(){
            var $this = $(this);
            $this.removeClass('btn-outline-dark')
            $this.addClass('btn-success')
            $this.html('در حال آماده‌سازی .. <i class="fa fa-spinner fa-spin align-self-center"></i>')
            window.location;

            myVar = setTimeout(function(){
                $this.addClass('btn-outline-dark')
                $this.removeClass('btn-success')
                $this.html('<i class="feather icon-download m-0 ml-1"></i> دانلود')
            }, 2000)
        }); {% endcomment %}
    }

    if ($('.js-example-basic-single').length) {
        $('.js-example-basic-single').select2(
            {
                allowClear: true,
                placeholder: "انتخاب کنید",
                "language": {
                    "noResults": function () {
                        return "موردی یافت نشد!</a>";
                    }
                },
                escapeMarkup: function (markup) {
                    return markup;
                }
            }
        );
    }

    if ($('.pro_filter_btn').length) {
        $('.pro_filter_btn').click(function () {
            $(this).toggleClass("active");
        });
    }

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').click(function () {
            setTimeout(function () {

                $('[data-toggle="tooltip"]').tooltip("hide")
            }, 500);

        });
    });

    {#jalaliDatepicker#}
    $(document).ready(function () {
        jalaliDatepicker.startWatch({ time: true });

    });

    // select2 in modals
        $('#send_by_sms').attr('checked', 'checked');
        
        $('select:not(.normal)').each(function () {
            $(this).select2({
                dropdownParent: $(this).parent(),
                placeholder: "انتخاب کنید",
                "language": {
                    "noResults": function () {
                        return "موردی یافت نشد!</a>";
                    }
                },
                escapeMarkup: function (markup) {
                    return markup;
                }
            });
        });
</script>

<script>
    ClassicEditor
        .create(document.querySelector('.ckeditor'), {
            language: {
                ui: 'fa',
                content: 'fa'
            }
        })
        .then(editor => {
            editor.ui.view.editable.element.parentElement.classList.add('ckeditor-custom-height');
        })
        .catch(error => {
            console.error(error);
        });
</script>

templates/dashboard/includes/sidebar.html
{% load static %}
<nav class="pcoded-navbar navbar-collapsed closed" id="sidebar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a class="b-brand">
                <div>
                    <img id="sidebar_logo" class="logo" src="{{ site.small_logo_light.url }}" loading="lazy"
                         alt="{{ site.title }}" style="width:45px">
                </div>
                <!-- <span class="b-title">داشبورد</span> -->
            </a>
            {% comment %} <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>{% endcomment %}
        </div>
        <div class="navbar-content scroll-div">
            <a href="#" id="close-mobile-collapse" class="d-flex w-100 mb-3 justify-content-center d-lg-none">
                <span class="feather icon-x align-self-center font-25 w-100 text-center"></span>
            </a>
            <ul class="nav pcoded-inner-navbar">
                {% if '/dashboard/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if request.path == '/dashboard/' %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:home' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="fas fa-home"></i>
                            </span>
                            <span class="pcoded-mtext">پیشخوان</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav pcoded-inner-navbar">
                {% if '/dashboard/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if request.path == '/dashboard/orders/' %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:orders' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="fas fa-store"></i>
                            </span>
                            <span class="pcoded-mtext">سفارشات</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav pcoded-inner-navbar">
                {% if '/dashboard/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if request.path == '/dashboard/products/' %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:products' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="fas fa-list"></i>
                            </span>
                            <span class="pcoded-mtext">محصولات</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav pcoded-inner-navbar">
                {% if '/dashboard/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if request.path == '/dashboard/coupons/' %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:coupons' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="fas fa-tag"></i>
                            </span>
                            <span class="pcoded-mtext">
                                تخفیف ها
                            </span>
                        </a>
                    </li>
                {% endif %}
            </ul>

            
            <ul class="nav pcoded-inner-navbar">
                {% if '/sell_control/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if request.path == '/dashboard/sell_control/' %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:sell-control-create-edit' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#878297" d="M353.4 32H94.7C42.6 32 0 74.6 0 126.6v258.7C0 437.4 42.6 480 94.7 480h258.7c52.1 0 94.7-42.6 94.7-94.6V126.6c0-52-42.6-94.6-94.7-94.6zm-50 316.4c-27.9 48.2-89.9 64.9-138.2 37.2-22.9 39.8-54.9 8.6-42.3-13.2l15.7-27.2c5.9-10.3 19.2-13.9 29.5-7.9 18.6 10.8-.1-.1 18.5 10.7 27.6 15.9 63.4 6.3 79.4-21.3 15.9-27.6 6.3-63.4-21.3-79.4-17.8-10.2-.6-.4-18.6-10.6-24.6-14.2-3.4-51.9 21.6-37.5 18.6 10.8-.1-.1 18.5 10.7 48.4 28 65.1 90.3 37.2 138.5zm21.8-208.8c-17 29.5-16.3 28.8-19 31.5-6.5 6.5-16.3 8.7-26.5 3.6-18.6-10.8 .1 .1-18.5-10.7-27.6-15.9-63.4-6.3-79.4 21.3s-6.3 63.4 21.3 79.4c0 0 18.5 10.6 18.6 10.6 24.6 14.2 3.4 51.9-21.6 37.5-18.6-10.8 .1 .1-18.5-10.7-48.2-27.8-64.9-90.1-37.1-138.4 27.9-48.2 89.9-64.9 138.2-37.2l4.8-8.4c14.3-24.9 52-3.3 37.7 21.5z"/></svg>                            </span>
                            <span class="pcoded-mtext">کنترل فروش</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav pcoded-inner-navbar">
                {% if '/dashboard/' in request.user_dashbords_path or request.has_admin_access %}
                    <li onclick="event.stopPropagation();"
                        data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                        class="nav-item {% if 'messages' in request.path  %}nav-active{% endif %}">
                        <a href="{% url 'dashboard:messages' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="fas fa-envelope"></i>
                            </span>
                            <span class="pcoded-mtext">پیام ها</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>