article/urls.py
from django.urls import path
from .views import (
                    ArticleView,
                    ArticleDetailView,
                    AuthorArticlesView,
                    ArticleTagView,
                    
)

app_name = 'article'

urlpatterns = [
    path('', ArticleView.as_view(), name='articles'),
    path('<str:slug>/', ArticleDetailView.as_view(), name='article-details'),
    path('author/<str:username>/', AuthorArticlesView.as_view(), name='author_articles'),
    path('tag/<str:tagname>/', ArticleTagView.as_view(), name='article-tag'),

]

core/urls.py
""" core URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps.sitemaps import *
from .sitemaps.views import *
# sitemaps = {
#     'posts': ArticleSitemap,
#     'products': ProductSitemap,
# }

urlpatterns = [


    path('admin/', admin.site.urls),


    
    path('ckeditor/', include('ckeditor_uploader.urls')),


    # Main urls
    path('', include('main.urls', namespace='main')),

    # Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    # article urls
    path('blog/', include('article.urls', namespace='article')),
    # game urls
    path('game/', include('game.urls')),

]

handler404 = 'main.views.handler404'

# Development
if bool(settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from jalali_date import datetime2jalali, date2jalali
from django.core.validators import MaxLengthValidator
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from .utils import upload_image_path, upload_video_path, upload_thumbnail_path
import math
from accounts.models import User  


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(publish=True)


class ArticleGeneral(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, \
                               verbose_name="نویسنده" ,blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        abstract = True

    def get_created_at(self):
        return datetime2jalali(self.created_at).strftime('%H:%M - %Y/%m/%d')

    get_created_at.short_description = 'تاریخ و زمان ایجاد'

    def get_created_at__date(self):
        return datetime2jalali(self.created_at).strftime('%Y/%m/%d')

    get_created_at__date.short_description = 'تاریخ ایجاد'

    def get_updated_at(self):
        return datetime2jalali(self.updated_at).strftime('%H:%M - %Y/%m/%d')

    get_updated_at.short_description = 'آخرین بروزرسانی'


class SEO(models.Model):
    meta_title = models.TextField(verbose_name="meta title (SEO)", validators=[MaxLengthValidator(60)], \
                                  null=True, help_text="حداکثر 60 کاراکتر")
    meta_description = models.TextField(verbose_name="meta description (SEO)", \
                                        validators=[MaxLengthValidator(160)], null=True, help_text="حداکثر 160 کاراکتر")

    class Meta:
        abstract = True


class Category(ArticleGeneral):
    title = models.CharField(null=True, max_length=128, verbose_name='عنوان')
    views = models.PositiveIntegerField(default=0, verbose_name='بازدیدها')
    slug = models.SlugField(max_length=128, blank=True, null=True, unique=True, \
                            allow_unicode=True, verbose_name='پیوند یکتا', help_text='این فیلد را خالی بگذارید.')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = ' دسته بندی‌ها'
        ordering = ('-created_at',)

    # get category names for category slugs
    def save(self, *args, **kwargs):
        if not self.slug:
            value = self.title
            self.slug = slugify(value, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        if self.title:
            return self.title
        return 'دسته بندی ناشناخته'

    def increment_views(self):
        self.views += 1
        self.save()

    @property
    def get_views(self):
        return self.views + 100


class Article(ArticleGeneral, SEO):
    created_at = models.DateTimeField(verbose_name='تاریخ ایجاد')
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, verbose_name="دسته بندی")
    title = models.CharField(max_length=225, null=True, verbose_name="عنوان مقاله")
    body = RichTextUploadingField(null=True, verbose_name="محتوای مقاله")

    thumbnail = models.ImageField(null=True, upload_to=upload_thumbnail_path, \
                                  verbose_name="تصویر شاخص",
                                  help_text="ابعاد عکس مربعی و حجم آن کمتر از 1 مگابایت باشد.")

    publish = models.BooleanField(default=True, verbose_name="در سایت منتشر شود", \
                                  help_text="غیرفعال بودن این فیلد به معنی پیش نویس بودن مقاله و عدم انتشار آن در سایت می‌باشد.")
    views = models.PositiveIntegerField(default=0, verbose_name="بازدیدها")
    slug = models.SlugField(max_length=225, null=True, blank=True, unique=True, allow_unicode=True,
                            verbose_name="پیوند یکتا")
    reed_time = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="مدت زمان خواندن متن")
    tags = models.ManyToManyField('ArticleTag', related_name='ArticleTag', blank=True, verbose_name="هشتگ‌ها")

    # Model managers
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = '    مقالات'
        ordering = ('-created_at',)

    def save(self, *args, **kwargs):
        if not self.slug:
            # set article slug from title
            article_title = self.title
            self.slug = slugify(article_title, allow_unicode=True)

        # Estimate article reed time
        body = self.body
        words_count = len(body.split())
        self.reed_time = math.ceil(words_count / 100)
        super(Article, self).save(*args, **kwargs)

    def increment_views(self):
        self.views += 1
        self.save()

    def __str__(self):
        return str(self.title)

    def get_views(self):
        return self.views + 100

    def get_absolute_url(self):
        return reverse("article:article-details", kwargs={"slug": self.slug})


# -------------------------------Article Comments-------------------------------
class ArticleComment(models.Model):
    body = models.TextField(max_length=300)
    # replyTo = models.ForeignKey('self', related_name='replays', blank=True, null=True, on_delete=models.PROTECT)
    # parent_id = models.PositiveSmallIntegerField(null=True, blank=True,)
    # parents_id = models.TextField(null=True, blank=True)
    # is_parent = models.BooleanField(default=False)
    created_at = models.DateTimeField(verbose_name='Created Date', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated Date',
                                      auto_now=True)  # تغییر از updated_at_at به updated_at
    created_by = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True)
    article = models.ForeignKey(Article, on_delete=models.PROTECT, related_name='comments', verbose_name='مقاله مربوطه')
    active = models.BooleanField(default=False)
    email = models.EmailField()

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        if self.created_by:
            return self.body + " ---------- " + self.created_by.get_username()
        return "unknown user comment"

    # def is_reply(self):
    #     return self.replyTo is not None


# tags in articles
class ArticleTag(SEO, models.Model):
    title = models.CharField(null=True, max_length=225, verbose_name='عنوان')
    description = RichTextField(blank=True, null=True, verbose_name='توضیحات')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, \
                                 blank=True, null=True, related_name="tags", verbose_name='دسته بندی')
    slug = models.SlugField(max_length=225, blank=True, null=True, \
                            unique=True, allow_unicode=True, verbose_name='پیوند یکتا')
    views = models.PositiveIntegerField(default=0, verbose_name='بازدیدها')
    created_at = models.DateTimeField(verbose_name='Created Date', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Updated Date', auto_now=True, null=True)

    class Meta:
        verbose_name = 'هشتگ'
        verbose_name_plural = 'هشتگ‌های مقالات'
        ordering = ('-views',)

    # get tag title for tag slugs
    def save(self, *args, **kwargs):
        if not self.slug:
            value = self.title
            self.slug = slugify(value, allow_unicode=True)
        super(ArticleTag, self).save(*args, **kwargs)

    def increment_views(self):
        self.views += 1
        if self.category:
            self.category.increment_views()
        self.save()

    def __str__(self):
        return self.title

    @property
    def get_views(self):
        return self.views + 100

    def get_absolute_url(self):
        return reverse("article:article-tag", kwargs={"tagname": self.slug})

article/forms.py
from .models import ArticleComment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = ArticleComment
        fields = ['body', 'email']  # فیلدهای مورد نیاز برای نمایش در فرم

article/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.db.models import Q
from datetime import datetime, timedelta
from .models import Article,Category,ArticleTag
from .forms import CommentForm
from django.shortcuts import render, redirect, get_object_or_404
from accounts.models import User
class ArticleView(generic.ListView):
    model = Article
    template_name = 'article/article_list.html'
    context_object_name = 'articles'
    paginate_by = 6

    def get_queryset(self):
        qs = self.model.published.all().order_by('-created_at')
        search = self.request.GET.get('q')
        category = self.request.GET.get('category')
        tag_filter = self.request.GET.get('article_tag', None)

        if search:
            qs = qs.filter(Q(title__icontains=search))
        if category:
            qs = qs.filter(category__slug=category)
        if tag_filter:
            article_tag = ArticleTag.objects.filter(Q(slug=tag_filter)).first()
            if article_tag:
                article_tag.increment_views()
                qs = qs.filter(tags=article_tag)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["top_articles_tags"] = ArticleTag.objects.all().order_by('-views')[:20]

        return context
class ArticleDetailView(generic.View):
    model = Article
    template_name = 'article/article_detail.html'
    form_class = CommentForm

    def get(self, request, slug):
        article = get_object_or_404(Article, slug=slug)
        comments = article.comments.filter(active=True)
        comment_form = self.form_class()  # Initialize an empty CommentForm

        return self.render_with_context(request, article, comments, comment_form)

    def post(self, request, slug):
        article = get_object_or_404(Article, slug=slug)
        comments = article.comments.filter(active=True)
        comment_form = self.form_class(request.POST)
        new_comment = None

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
            comment_form = self.form_class()  # Initialize an empty CommentForm after submission

        return self.render_with_context(request, article, comments, comment_form, new_comment)

    def render_with_context(self, request, article, comments, comment_form, new_comment=None):
        context = self.get_context_data(article, comments, comment_form, new_comment)
        # Loop through comments to check for replies

        return render(request, self.template_name, context)

    def get_context_data(self, article, comments, comment_form, new_comment=None):
        context = {
            'article': article,
            'comments': comments,
            'comment_form': comment_form,
            'top_article_tags': ArticleTag.objects.all().order_by('-views')[:20],
            'top_articles': Article.published.all().order_by('-views')[:4],
            'top_categories': Category.objects.all().order_by('-views'),
            'last_articles': Article.published.all().order_by('-created_at')[:10],

            'articles_count': Article.published.count(),
            # 'comment_count': ArticleComment.published.count(),

        }
        if new_comment is not None:
            context['new_comment'] = new_comment
        return context


class AuthorArticlesView(generic.ListView):
    model = Article
    template_name = 'article/article_list.html'
    context_object_name = 'articles'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_username = self.kwargs.get('username')
        author = get_object_or_404(User, username=author_username)
        context['author'] = author
        return context

    def get_queryset(self):
        qs = self.model.published.all().order_by('-created_at')
        author_username = self.kwargs.get('username')

        if author_username:
            author = get_object_or_404(User, username=author_username)
            qs = qs.filter(author=author)

        return qs


class ArticleTagView(generic.ListView):
    model = Article
    template_name = 'article/articles.html'
    context_object_name = 'articles'
    paginate_by = 12
    page_name = "بلاگ"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_name"] = self.page_name
        context["top_articles"] = self.get_queryset().order_by('-views')[:4]
        context["articles_count"] = self.get_queryset().count()
        context["top_articles_tags"] = ArticleTag.objects.all().order_by('-views')[:20]
        context["article_tags"] = ArticleTag.objects.all()  # Fetch all article tags

        tag_name = self.kwargs.get('tagname')
        filtered_tag = ArticleTag.objects.filter(slug=tag_name).first()
        if filtered_tag:
            filtered_tag.increment_views()
            context["filtered_tag"] = filtered_tag

        return context

    def get_queryset(self):
        queryset = self.model.published.all()

        # Get the tagname from URL parameters
        tag_name = self.kwargs.get('tagname')

        # Filter ArticleTag based on the tagname
        filtered_tag = ArticleTag.objects.filter(slug=tag_name).first()

        if filtered_tag:
            # If the tag exists, increment its views
            filtered_tag.increment_views()
            # Filter articles based on the filtered tag
            queryset = queryset.filter(tags=filtered_tag)

        return queryset

article/templates/article/article_detail.html
{% extends 'layouts/base.html' %}
{% load static  %}
{% block title %}
    {{ article.meta_title }} | فروشگاه اینترنتی الورول
{% endblock title %}

{% block css %}



<style>
    
</style>
{% endblock css %}

{% block meta %}
    <meta name="keywords" content="{{ article.meta_title }}">
    <meta property="og:title" content="{{ article.meta_title }}"/>
    <meta name="description" content="{{ article.meta_description }}" />
    <meta property="og:locale" content="fa_IR" />
    <meta property="og:type" content="article" />
    <meta property="og:description" content="{{ article.meta_description }}"/>
    <meta property="og:site_name" content="فروشگاه اینترنتی الورول" />
    <meta name="twitter:card" content="summary_large_image" />
{% endblock meta %}

{% block content %}


    <main class="cart-page default ">
        <div class="container">
            <div class="row">

                <div class="single_blog_content col-12 col-lg-9 mx-auto">
                    <header class="card-header">
                        <h1 class="card-title font-weight-bold font-18">
                            {{ article.meta_title }}
                        </h1>
                    </header>
                    <div class="single_blog_page">

                        <div class="single_blog_box_content">
                            <form class="form-account">
                                <div class="row">

                                    <div class="col-md-12 col-sm-12">

                                        <img src="{{ article.thumbnail.url }}" style="width:800px;height:500px" />
                                        <div class="data_det">
                                        <span class="publish_date">
                                            <i class="fa fa-clock"></i>
                                            {{ article.get_created_at }}
                                        </span>
                                            <span class="author">
                                            <i class="fa fa-user-alt"></i>
                                                {%  if article.author %}
                                                    <a href="{% url 'article:author_articles' article.author %}">{{ article.author }}</a>
                                                {% else %}
                                                    فروشگاه اینترنتی الورول
                                                {% endif %}
                                        </span>
                                            <span class="categoey">
                                            <i class="fa fa-folder"></i>
                                            <a href="{% url 'article:articles' %}" rel="category tag">مقالات</a>
                                        </span>
                                            <span class="visitors">
                                            <i class="fa fa-eye"></i> 1725 بازدید
                                        </span>
                                        </div>
                                        <div class="text-justify single_blog_page">
                                            {{ article.body | safe }}
                                        </div>

                                    </div>



                                </div>
                            </form>
                        </div>
                    </div>
                </div>


                <div class="col-12 col-lg-3">

                    <div class="sidebar_blog">
                        <div class="widget_blog">
                            <div class="widget_blog_headbox">
                                <h3> دسته بندی ها </h3>
                            </div>
                            <div class="blog_list_widget_blog">
                                <div class="widget_blog_groups">
                                    <ul class="widget_blog_posts">
                                        <ul>
                                            {% for category in top_categories %}
                                                <li>
                                                    <a class="widget_blog_title_link" href="{% url 'article:articles' %}?category={{ category.slug }}">{{ category.title }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>

                                    </ul>

                                </div>
                            </div><!-- end blog-list -->
                        </div>
                        <div class="widget_blog marg_top20">
                            <div class="widget_blog_headbox">
                                <h3>آخرین مقالات </h3>
                            </div>
                            <div class="blog_list_widget_blog">
                                <div class="widget_blog_groups">
                                    <ul class="widget_blog_posts">
                                        {% for article in last_articles %}
                                            <li><a class="widget_blog_title_link" href="{{article.get_absolute_url}}"> {{article.title}}</a></li>
                                        {% endfor%}
                                    </ul>
                                </div>
                            </div><!-- end blog-list -->
                        </div>

                    </div>
                </div>




            </div>
        </div>

    </main>


{% endblock content %}

article/templates/article/article_list.html
{% extends "layouts/base.html" %}
{% load static  %}

{% block title %}
    وبلاگ | {{site_info.name}}
{% endblock %}

{% block meta %}
    <link rel="canonical" href="{{ request.build_absolute_uri }}" />
    {% if page_obj.has_next %}
        <link rel="next" href="blackdesiner.ir/blog/?page={{ page_obj.next_page_number }}" />
    {% endif %}
    <meta property="og:locale" content="fa_IR" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Blog | {{site_info.name}}" />
    <meta property="og:url" content="https://blackdesiner.ir/blog/" />
    <meta property="og:site_name" content="{{site_info.name}}" />
    <meta name="twitter:card" content="summary_large_image" />
{% endblock meta %}


{% block style %}

{% endblock style %}

{% block content %}
{#<ul>#}
{#  {% for tag in top_articles_tags %}#}
{#    <li><a href="{% url 'articles:article-tag' tag.slug %}">{{ tag.title }}</a></li>#}
{#  {% endfor %}#}
{#</ul>#}

    <main class="category-blog default space-top-30">
        <div class="container ">

            <div class="row">
                <div class="col-12">
                    <nav>
                        <ul class="breadcrumb">
                            <li>
                                <i class="fa fa-home" aria-hidden="true"></i>
                            </li>


                            <li>
                                <a href="#"><span>
                                وبلاگ
                            </span></a>
                            </li>

                        </ul>
                    </nav>
                </div>
                <div class="single_blog_content cat_blog_content col-12 col-lg-9 mx-auto order-1 order-sm-1 ">



                    <div class="row listing-items Blog-category">
                        {% if articles %}

                            {% for article in articles %}
                                <div class="col-xl-6 col-lg-6 col-md-6 col-12  ">
                                    <div class="blog_tag">
                                        <a href="{{article.get_absolute_url}}">
                                            <img src="{{article.thumbnail.url}}" class="img-fluid" alt="{{article.title}}" load="lazy">
                                        </a>
                                        <a href="{{article.get_absolute_url}}">
                                            <h2 class="Blog_title">
                                                {{article.title}}
                                            </h2>
                                        </a>
                                        <div class="Blog_list">
                                    <span class="Blog_author">
                                        <i class="fa fa-user"></i>
                                        {% if article.author %}
                                        <a href="{% url 'article:author_articles' article.author %}">{{ article.author }}</a>
                                        {% else %}
{{site_info.name}}
                                        {% endif %}
                                    </span>
                                            <span class="Blog_Date">
                                        <i class="fa fa-calendar "></i>
                                        {{article.get_created_at_jalali}}
                                    </span>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-12 text-center">
                                <p>مقاله‌ای یافت نشد.</p>
                            </div>
                        {% endif %}

                    </div>

                    {% include 'includes/pagination.html' %}

                </div>
                <div class="col-12 col-lg-3 ">

                    <div class="sidebar_blog">
                        <div class="widget_blog">
                            <div class="widget_blog_headbox">
                                <h3> دسته بندی ها </h3>
                            </div>
                            <div class="blog_list_widget_blog">
                                <div class="widget_blog_groups">
                                    <ul class="widget_blog_posts">
                                        {% for item in product_categories %}
                                            <li><a href="{% url "products:products-category" item.slug %}"
                                                   class="widget_blog_title_link"> {{ item.title }} </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div><!-- end blog-list -->
                        </div>
                        <div class="widget_blog marg_top20">
                            <div class="widget_blog_headbox">
                                <h3>آخرین مقالات </h3>
                            </div>
                            <div class="blog_list_widget_blog">
                                <div class="widget_blog_groups">
                                    <ul class="widget_blog_posts">
                                        {% if articles %}

                                            {% for article in articles %}
                                                <li>
                                                    <a class="widget_blog_title_link" href="{{article.get_absolute_url}}">
                                                        {{article.title}}
                                                    </a>
                                                </li>

                                            {% endfor %}
                                        {% else %}
                                            <div class="col-12 text-center">
                                                <p>مقاله‌ای یافت نشد.</p>
                                            </div>
                                        {% endif %}

                                    </ul>
                                </div>
                            </div><!-- end blog-list -->
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </main>





{% endblock content %}