core/urls.py
""" core URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps.sitemaps import *
from .sitemaps.views import *
# sitemaps = {
#     'posts': ArticleSitemap,
#     'products': ProductSitemap,
# }

urlpatterns = [


    path('admin/', admin.site.urls),


    
    path('ckeditor/', include('ckeditor_uploader.urls')),


    # Main urls
    path('', include('main.urls', namespace='main')),

    # Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    # article urls
    path('blog/', include('article.urls', namespace='article')),
    # game urls
    path('game/', include('game.urls')),

]

handler404 = 'main.views.handler404'

# Development
if bool(settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . views import *

app_name = 'dashboard'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('messages/', MessagesView.as_view(), name='messages'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),

]

dashboard/models.py
from django.db import models

main/models.py
from django.db import models
from jalali_date import datetime2jalali, date2jalali
from django.core.validators import MaxLengthValidator
from accounts.validators import phone_number_validator
from .utils import upload_logo_path


class General(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        abstract = True

    def get_created_at(self):
        return datetime2jalali(self.created_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ ایجاد'

    def get_updated_at(self):
        return datetime2jalali(self.updated_at).strftime('%H:%M - %Y/%m/%d')
    get_updated_at.short_description = 'آخرین بروزرسانی'


class SEO(models.Model):
    meta_title = models.TextField(verbose_name="meta title (SEO)", validators=[MaxLengthValidator(160)], \
                                  null=True, help_text="حداکثر 160 کاراکتر")
    meta_description = models.TextField(verbose_name="meta description (SEO)", \
                                        validators=[MaxLengthValidator(160)], null=True, help_text="حداکثر 160 کاراکتر")


# ----------------SMS log---------------------
class SmsLog(General):
    SUBJECT_CHOICES = [
        ('phone_verify', 'تایید موبایل'),
        ('email_verify', 'تایید ایمیل'),
        ('birth_date', 'تبریک تولد'),
        ('new_order_customer', 'سفارش جدید (به مشتری)'),
        ('new_order_admin', 'سفارش جدید (به ادمین)'),
        ('other', 'سایر'),
    ]

    phone = models.CharField(max_length=20, null=True, blank=True)
    user = models.ForeignKey('accounts.User', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='کاربر')
    subject = models.CharField(max_length=30, choices=SUBJECT_CHOICES, default='other', verbose_name='موضوع')
    is_sent = models.BooleanField(default=True, verbose_name='وضعیت ارسال')
    status_code = models.PositiveSmallIntegerField(null=True, verbose_name='کد وضعیت')
    description = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'تاریخچه sms'
        verbose_name_plural = 'تاریخچه sms ها'


    # ---------------------contact form model------------------------------------------------


class ContactMessage(models.Model):
    STATUS_CHOICES = (
        ('not_seen', 'جدید'),
        ('seen', 'خوانده شده'),
    )

    name = models.CharField(max_length=100, null=True, blank=True, verbose_name='نام')
    email = models.EmailField(verbose_name='ایمیل')
    subject = models.CharField(max_length=200, verbose_name='موضوع')
    message = models.TextField(verbose_name='پیام')
    created_at = models.DateTimeField(auto_now_add=True , verbose_name='تاریخ ایجاد')
    phone = models.CharField("تلفن همراه", null=True, max_length=11, \
                             validators=[phone_number_validator], blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='not_seen',verbose_name='وضعیت')
    seen_at = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ مشاهده')  # Add this line

    class Meta:
        verbose_name = 'پیام ارتباط با ما'
        verbose_name_plural = 'پیام های ارتباط با ما'
        ordering = ('-created_at',)

    def get_created_at(self):
        return datetime2jalali(self.created_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ ایجاد'
    def get_seen_at(self):
        return datetime2jalali(self.seen_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ مشاهده'

    def __str__(self):
        return self.name
# -------------------------site settings ---------------------------------------------

dashboard/forms.py
from django import forms
from .models import SellControl


class SellControlForm(forms.ModelForm):
    class Meta:
        model = SellControl
        fields = ('is_open', )

dashboard/views.py
from django.db.models.aggregates import Sum, Count
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from .models import *
from accounts.models import *
from accounts.mixins import *
from django.db.models import Q, Count
from django.http import HttpResponse
from jalali_date import datetime2jalali, date2jalali
from datetime import datetime, timedelta
import csv, xlwt
import pandas as pd
from django.contrib import messages

from main.models import ContactMessage
from site_info.models import SiteInfo


# --------------------------------- Home View ---------------------------------
class HomeView(LoginRequiredMixin, AdminAccessMixin, generic.TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        today = datetime.today().date()
        context = super().get_context_data(**kwargs)
        context["customers_count"] = User.objects.count()

        return context



# --------------------------------messages views--------------------------------------
class MessagesView(LoginRequiredMixin, AdminAccessMixin, generic.ListView):
    model = ContactMessage
    template_name = 'dashboard/messages/messages.html'
    context_object_name = 'contact_messages'
    paginate_by = 50

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'پیام'
        context["object_name_fa_plural"] = 'پیام ها'
        context['objects_count'] = self.get_queryset().count()

        return context
    def get_queryset(self):
        queryset = super().get_queryset()
        search_filter = self.request.GET.get('search', None)
        status_filter = self.request.GET.get('status', None)

        if status_filter:
            if status_filter in dict(ContactMessage.STATUS_CHOICES).keys():
                queryset = queryset.filter(status=status_filter)

        if search_filter:
            queryset = queryset.filter(Q(code__icontains=search_filter))


        return queryset


class MessageDetailView(LoginRequiredMixin, AdminAccessMixin, generic.DetailView):
    model = ContactMessage
    template_name = 'dashboard/messages/message_detail.html'
    context_object_name = 'message'
    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'پیام'
        context["object_name_fa_plural"] = 'پیام ها'

        return context
    def get_object(self):
        obj = super().get_object()
        # Mark as seen if not already seen
        if obj.status == 'not_seen':
            obj.status = 'seen'
            obj.seen_at = timezone.now()
            obj.save()
        return obj


# --------------------------------- Orders View ---------------------------------
class OrderView(LoginRequiredMixin, AdminAccessMixin, generic.ListView):
    model = SiteInfo
    template_name = 'dashboard/site/site.html'
    context_object_name = 'orders'
    paginate_by = 10

    def get_shared_context(self, context):
        context["object_name_fa"] = 'سفارش'
        context["object_name_fa_plural"] = 'سفارشات'

        return context

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)
        context["object_name_fa"] = 'سفارش'
        context["object_name_fa_plural"] = 'سفارشات'
        context['objects_count'] = self.get_queryset().count()
        context['users'] = User.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        user_filter_id = self.request.GET.get('user_filter', None)
        is_paid = self.request.GET.get('is_paid', None)
        status = self.request.GET.get('status', None)
        delivery_option = self.request.GET.get('delivery_option', None)
        search = self.request.GET.get('search', None)

        if user_filter_id and user_filter_id != 'all':
            queryset = queryset.filter(user__id=user_filter_id)

        if is_paid and is_paid != 'None':
            is_paid = is_paid == 'True'
            queryset = queryset.filter(is_paid=is_paid)

        if status and status != 'all':
            queryset = queryset.filter(shipping_status=status)

        if delivery_option and delivery_option != 'all':
            queryset = queryset.filter(delivery_option=delivery_option)

        if search:
            queryset = queryset.filter(Q(code__icontains=search))

        return queryset


class OrderUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = SiteInfo
    fields = ('name', 'logo', 'email', 'phone', 'is_paid',
              'address', 'description', )

    template_name = 'dashboard/site/site.html'
    success_message = 'تغییرات ثبت گردید'

    def get_success_url(self):
        return reverse('dashboard:site')

    def form_valid(self, form):

        return super().form_valid(form)

    def form_invalid(self, form):
        # Add errors to messages
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{form.fields[field].label}: {error}")

        return self.form_invalid_redirect()

    def form_invalid_redirect(self):
        return redirect(reverse('dashboard:site'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_name_fa'] = 'سفارش'
        context['object_name_fa_plural'] = 'سفارشات'
        context['users'] = User.objects.all()

        return context

dashboard/templates/dashboard/messages/filters.html
<form method="GET" action="." >
    <div class="row  justify-content-start align-items-center mb-3">
        <div class="col-sm-2 d-flex justify-content-end m-1">
            <h5 class=" text-info">فیلتر بر حسب:</h5>
        </div>

        <div class="col-sm-2 m-1">
            <select name="status" id="status" class="form-select">
                <option value="all">وضعیت(همه)</option>
                <option value="seen" {% if request.GET.status == 'seen' %}selected{% endif %}>خوانده شده</option>
                <option value="not_seen" {% if request.GET.status == 'not_seen' %}selected{% endif %}>جدید </option>
            </select>
        </div>


        <div class="col-sm-1   justify-content-end m-1">
            <button type="submit" class="btn btn-info">فیلتر
                <i class="fas fa-filter"></i>
            </button>
        </div>
    </div>
</form>

dashboard/templates/dashboard/messages/message_detail.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% load humanize %}


{% block title %}
    بررسی پیام {{ message }}
{% endblock %}


{% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'dashboard:messages' %}">لیست {{ object_name_fa_plural }}</a></li>
        <li class="breadcrumb-item"><a href="{{ request.path }}">بررسی پیام {{ message }}</a></li>
{% endblock breadcrumb %}

{% block content %}
    <div class="main-body">
        <div class="page-wrapper">
            <div class="card card-default mt-2">
                <div class="card-header">
                    <h5>جزئیات {{ object_name_fa }}</h5>
                    {% include 'dashboard/coupons/add_coupon.html' %}
                </div>

                <div class="container mt-4">

                    <div class="card shadow-sm border-primary">
                        <div class="card-header bg-primary text-white text-right">
                            <h2>
                                <i class="fas fa-envelope"></i> {{ message.subject|slice:":30" }}{% if message.subject|length > 30 %}...{% endif %}
                            </h2>
                        </div>
                        <div class="card-body">
                            <p><i class="text-info fas fa-user"> نام:</i> {{ message.name|default:"نامشخص" }}</p>
                            <p><i class="text-info fas fa-at"> ایمیل:</i> {{ message.email }}</p>
                            <p><i class="text-info fas fa-phone"> تلفن: </i>  {{ item.phone|default:'ثبت نشده' }}</p>
                            <p><i class="text-info fas fa-calendar"> تاریخ دریافت:</i> {{ message.get_created_at }}</p>
                            <p><i class="text-info fas fa-info-circle"> وضعیت:</i>  {{ message.get_status_display }}</p>
                            <p><i class="text-info fas fa-comment-dots"> محتوا:</i></p>
                            <div class="border p-3 rounded bg-light  mx-auto m-2">
                                {{ message.message }}
                            </div>
                            {% if message.seen_at %}
                                <p><i class="text-info fas fa-calendar-check">تاریخ مشاهده:</i>  {{ message.get_seen_at }}</p>
                            {% else %}
                                <p><i class="text-info fas fa-calendar-times"> تاریخ مشاهده:</i> هنوز مشاهده نشده</p>
                            {% endif %}
                        </div>
                        <div class="card-footer text-right">
                            <a href="{% url 'dashboard:messages' %}" class="btn btn-primary"><i class="fas fa-arrow-left"></i> بازگشت به لیست پیام‌ها</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}

dashboard/templates/dashboard/messages/messages.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% load humanize %}


{% block title %}
    لیست {{ object_name_fa_plural }}
{% endblock %}


{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ request.path }}">لیست {{ object_name_fa_plural }}</a></li>
{% endblock breadcrumb %}


{% block content %}
    <div class="main-body">
        <div class="page-wrapper">
            <div class="card card-default mt-2">
                <div class="card-header">
                    <h5>لیست {{ object_name_fa_plural }}</h5>
                    {% include 'dashboard/coupons/add_coupon.html' %}
                </div>
                <div class="card-body">
                    {% include './filters.html' %}
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="row">
                            {#                            <div class="col-md-12">#}
                            {#                                {% include "./search.html" %}#}
                            {#                            </div>#}
                            <div class="col-12 col-md-2">
                                {% comment %} <a href="" class="btn btn-success mb-3 w-100" data-toggle="modal" data-target="#item_add">
                                <i class="fa fa-plus font-17 mx-2" ></i>
                                افزودن {{ object_name_fa }} جدید
                            </a> {% endcomment %}
                                {{ form.errors }}
                            </div>

                            {% comment %} <div class="col-md-10">
                            {% include "./search.html" %}
                        </div> {% endcomment %}
                            <div class="col-sm-12 table-responsive" style="overflow-y: scroll;">
                                <table id="sortable-table" class="table table-bordered" role="grid" aria-describedby="datatable-checkbox_info">
                                    <thead>
                                    <tr>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-user"></i> فرستنده
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-envelope"></i> ایمیل
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-phone"></i> تلفن
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-tag"></i> موضوع
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-comment"></i> پیام
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-info-circle"></i> وضعیت
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-calendar"></i> تاریخ ارسال
                                        </th>
                                        <th class="text-center" style='min-width:150px'>
                                            <i class="fas fa-eye"></i> مشاهده
                                        </th>


                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for item in contact_messages %}
                                        <tr data-id="{{ item.id }}">
                                            <td>{{ item.name }}</td>
                                            <td>{{ item.email }}</td>
                                            <td>{{ item.phone|default:'-' }}</td>
                                            <td>{{ item.subject }}</td>

                                            <td>{{ item.message|striptags|safe|truncatewords:12 }}...</td>


                                            <td class="text-center">
                                                {% if item.status == 'seen' %}
                                                    <span class="badge badge-success p-2">خوانده شده</span>
                                                {% else %}
                                                    <span class="badge badge-danger p-2">جدید</span>
                                                {% endif %}
                                            </td>
                                            <td>{{ item.get_created_at }}</td>
                                            <td><a href="{% url 'dashboard:message_detail' item.id %}" title="مشاهده پیام" class=" text-info h4"> <i class="fas fa-eye"></i></a></td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% include "includes/pagination.html" %}
                                <span>{{ objects_count }} مورد یافت شد.</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock content %}

dashboard/templates/dashboard/messages/search.html
<div class="mb-4">
    <form method="GET" action=".">
        <div class="d-flex justify-content-start align-items-center">
            <div class="m-1 w-25">
                <input type="text" name="search" id="search" class="form-control" placeholder="کد کوپن را وارد کنید" value="{{ request.GET.search }}">
            </div>
            <div class="m-1">
                <button type="submit" class="btn btn-info">جستجو
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</div>