core/urls.py
""" core URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps.sitemaps import *
from .sitemaps.views import *
# sitemaps = {
#     'posts': ArticleSitemap,
#     'products': ProductSitemap,
# }

urlpatterns = [


    path('admin/', admin.site.urls),


    
    path('ckeditor/', include('ckeditor_uploader.urls')),


    # Main urls
    path('', include('main.urls', namespace='main')),

    # Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    # article urls
    path('blog/', include('article.urls', namespace='article')),
    # game urls
    path('game/', include('game.urls')),

]

handler404 = 'main.views.handler404'

# Development
if bool(settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (
    HomeView,
    AboutView,
    ContactView,
    PrivicyView,
    Privicy2View,
    EduView,
    DiseView,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('درباره-ما/', AboutView.as_view(), name='about'),
    path('edu/', EduView.as_view(), name='edu'),
    path('privacy/', PrivicyView.as_view(), name='privacy'),
    path('تماس-با-ما/', ContactView.as_view(), name='contact'),
    path('سیاست-حفظ-حریم-خصوصی-2/', Privicy2View.as_view(), name='privacy2'),
    path('dise/', DiseView.as_view(), name='dise'),
]

main/models.py
from django.db import models
from jalali_date import datetime2jalali, date2jalali
from django.core.validators import MaxLengthValidator
from accounts.validators import phone_number_validator
from .utils import upload_logo_path


class General(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')

    class Meta:
        abstract = True

    def get_created_at(self):
        return datetime2jalali(self.created_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ ایجاد'

    def get_updated_at(self):
        return datetime2jalali(self.updated_at).strftime('%H:%M - %Y/%m/%d')
    get_updated_at.short_description = 'آخرین بروزرسانی'


class SEO(models.Model):
    meta_title = models.TextField(verbose_name="meta title (SEO)", validators=[MaxLengthValidator(160)], \
                                  null=True, help_text="حداکثر 160 کاراکتر")
    meta_description = models.TextField(verbose_name="meta description (SEO)", \
                                        validators=[MaxLengthValidator(160)], null=True, help_text="حداکثر 160 کاراکتر")


# ----------------SMS log---------------------
class SmsLog(General):
    SUBJECT_CHOICES = [
        ('phone_verify', 'تایید موبایل'),
        ('email_verify', 'تایید ایمیل'),
        ('birth_date', 'تبریک تولد'),
        ('new_order_customer', 'سفارش جدید (به مشتری)'),
        ('new_order_admin', 'سفارش جدید (به ادمین)'),
        ('other', 'سایر'),
    ]

    phone = models.CharField(max_length=20, null=True, blank=True)
    user = models.ForeignKey('accounts.User', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='کاربر')
    subject = models.CharField(max_length=30, choices=SUBJECT_CHOICES, default='other', verbose_name='موضوع')
    is_sent = models.BooleanField(default=True, verbose_name='وضعیت ارسال')
    status_code = models.PositiveSmallIntegerField(null=True, verbose_name='کد وضعیت')
    description = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'تاریخچه sms'
        verbose_name_plural = 'تاریخچه sms ها'


    # ---------------------contact form model------------------------------------------------


class ContactMessage(models.Model):
    STATUS_CHOICES = (
        ('not_seen', 'جدید'),
        ('seen', 'خوانده شده'),
    )

    name = models.CharField(max_length=100, null=True, blank=True, verbose_name='نام')
    email = models.EmailField(verbose_name='ایمیل')
    subject = models.CharField(max_length=200, verbose_name='موضوع')
    message = models.TextField(verbose_name='پیام')
    created_at = models.DateTimeField(auto_now_add=True , verbose_name='تاریخ ایجاد')
    phone = models.CharField("تلفن همراه", null=True, max_length=11, \
                             validators=[phone_number_validator], blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='not_seen',verbose_name='وضعیت')
    seen_at = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ مشاهده')  # Add this line

    class Meta:
        verbose_name = 'پیام ارتباط با ما'
        verbose_name_plural = 'پیام های ارتباط با ما'
        ordering = ('-created_at',)

    def get_created_at(self):
        return datetime2jalali(self.created_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ ایجاد'
    def get_seen_at(self):
        return datetime2jalali(self.seen_at).strftime('%H:%M - %Y/%m/%d')
    get_created_at.short_description = 'تاریخ مشاهده'

    def __str__(self):
        return self.name
# -------------------------site settings ---------------------------------------------

main/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='نام', max_length=100)
    email = forms.EmailField(label='ایمیل')
    phone = forms.CharField(label='تلفن', max_length=15, required=False)
    subject = forms.CharField(label='موضوع', max_length=200)
    message = forms.CharField(label='پیام', widget=forms.Textarea)

main/views.py
from django.db.models import Q,F
from django.views import generic
from django.shortcuts import render
from datetime import datetime, timedelta
from .forms import ContactForm
from django.contrib import messages
from .models import ContactMessage  
# import pandas as pd
import os, csv, io
from django.http import *
import random



def handler404(request, exception, template_name="404.html"):
    return render(request, template_name)


class HomeView(generic.TemplateView):
    template_name = 'main/home.html'




class AboutView(generic.TemplateView):
    template_name = 'main/about.html'


class DiseView(generic.TemplateView):
    template_name = 'main/dise.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Check if 'roll' is present in the GET parameters to trigger a dice roll
        if 'roll' in self.request.GET:
            # Simulate rolling a 6-sided dice
            context['roll_value'] = random.randint(1, 6)
            if context['roll_value']  == 6 :
                context['result'] = 'شما برنده شدید'
            else:
                context['result'] = 'هفته بعد شاید برنده بشی . این هفته که نشد. '

        else:
            context['roll_value'] = None

        return context

class EduView(generic.TemplateView):
    template_name = 'main/edu.html'

class PrivicyView(generic.TemplateView):
    template_name = 'main/privacy.html'
    
class Privicy2View(generic.TemplateView):
    template_name = 'main/privacy2.html'


class ContactView(generic.FormView):
    template_name = 'main/contact.html'
    form_class = ContactForm
    success_url = '/success/'  # URL صفحه موفقیت

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']

        try:
            # ذخیره اطلاعات در مدل ContactMessage
            contact_message = ContactMessage(
                name=name,
                email=email,
                phone=phone,
                subject=subject,
                message=message
            )
            contact_message.save()

            # نمایش پیغام موفقیت
            messages.success(self.request, 'پیغام شما با موفقیت ارسال شد.')

        except Exception as e:
            # نمایش پیغام خطا
            messages.error(self.request, 'خطایی در ارسال پیغام رخ داد. لطفا دوباره تلاش کنید.')
            print(e)  # چاپ خطا برای بررسی

        # بازگشت به صفحه فعلی
        return self.render_to_response(self.get_context_data(form=form))

main/templates/main/about.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}
    درباره ما | {{ site_info.name }}
{% endblock title %}

{% block content %}

<main class="cart-page">

  <div class="container">
    <div class="row">
        <div class="contact_us_content col-12 mx-auto">
            <header class="card-header">
                <h3 style="" class="card-title"><span>
                  گروه بازرگانی آتا
               
                </span>
              </h3>
            </header>
            <div class="account-box contact_us_page">

                <div class="account-box-content">
                    <form class="form-account">
                      
                      <p class="text-justify">گروه بازرگانی آتا (مجموعه‌های تخصصی الورول و آتاپرینتر) با سابقه درخشان خود علاوه بر تولید رول‌های حرارتی در زمینه واردات این رول‌ها و توزیع آن سال‌ها پیشگام بوده است. <br> ما موفقیت خود را مدیون نخستین هدفی هستیم که بر پایه آن فعالیت می‌کنیم. به عبارت ساده‌تر با ارائه ضمانت محصولات خود این نوید را داده‌ایم که رضایت مشتریانمان نقطه قوت عملکرد مجموعه الورول است. از طرفی تلاشمان ارائه محصولاتی باکیفیت در عین حال با قیمتی مناسب بوده است.</p>

  <h2 class="">محصولات و فعالیت مجموعه الورول:</h2>
  <ul class="text-justify">
    <li>واردات، تولید و توزیع انواع رول حرارتی: (کاغذ فیش پرینتر- نوبت‌دهی- رول بانکی (ATM)- رول پوز (POS)- رول صندوق فروشگاهی- رول انواع دستگاه‌های آزمایشگاهی) (به صورت عمده)</li>
    <li>واردکننده تخصصی انواع ریبون‌های لیبل پرینتر: (وکس- وکس رزین- رزین) در ابعاد مختلف</li>
    <li>نماینده کارخانجات لیبل</li>
    <li>تهیه و توزیع انواع لیبل به صورت تخصصی: (لیبل کاغذی- لیبل حرارتی- لیبل پی‌وی‌سی- لیبل متال- تایوک- اسکراچ)</li>
  </ul>

  <h2 class="">اهداف ما در الورول:</h2>
<p class="text-justify">بخش مدیریت:<br>
   مدیر عامل و هیئت مدیره الورول بر آن هستند تا رسالت همیشگی خود را که همان اصل مشتری مداری است، در تمام زمینه‌های کاری رعایت و اجرا شود.<br>

بخش فروش و بازاریابی:<br>
 با بهره گیری از کادری مجرب و حرفه‌ای اصل مشتری مداری را سر لوحه کار خود قرار داده‌ایم. از طرفی تیم بازاریابی الورول با تحقیق و بررسی نیازهای روز مشتریان اعم از شرکت‌های دولتی و خصوصی و هم چنین مشاغل اداری و تجاری سعی در برآوردن این نیازها دارند.

واحد مالی و حسابداری: تیم حسابداری ما با همکاری مسئولین واحد انبار مغایرت‌های احتمالی را رفع می‌کنند. از طرفی با بررسی‌های به موقع وضعیت موجودی انبار را چک می‌کنند تا با عدم موجودی کالا مواجه نشویم.<br>

واحد بازرگانی(داخلی-خارجی):<br>
 برنامه‌های سازمان توسط مدیر بازرگانی در مسیر رسیدن به اهداف درازمدت مجموعه اجرا می‌شود. امور مربوط به صادرات و واردات به درستی سازماندهی خواهد شد که همین موضوع موفقیت ما را به ارمغان آورده است.<br>

واحد پشتیبانی سایت و سوشال مارکتینگ:<br>
 کارشناسان پشتیبانی سایت ما در ساعات اداری آماده ارائه مشاوره‌های لازم و رفع سوالات شما عزیزان هستند. بعلاوه گروه سوشال مارکتینگ در راستای اطلاع‌رسانی و ارتباط با مشتریان فعالیت می‌کنند.<br>

انبار و حمل‌ونقل:<br>
 امور انبارداری و حمل‌ونقل کالا توسط تیمی مجرب انجام می‌گیرد. بنابراین هیچ گونه نگرانی جهت سلامت کالا متوجه شما نخواهد شد.<br>

واحد رضایت مشتری و نظرسنجی:<br>
 ما در ابتدای تأسیس بازرگانی آتا الویت کار خود را بر رضایت مشتری قرار دادیم. از این رو تمام تلاش خود را به خرج دادیم تا به این مهم دست پیدا کنیم. حتی در این مسیر برای اطمینان بیشتر از نظرسنجی‌ها نیز کمک گرفتیم.<br>

فروشگاه اینترنتی:<br>
 فروش آنلاین در الورول سعی بر آن دارد تا همانند فروش سنتی مجموعه در بهترین شکل ممکن به ارائه خدمات مشتریان خود بپردازد. از طرفی خرید اینترنتی را در هر کجای ایران ممکن سازد .<br>

الورول سرمایه اصلی خود را مشتریان همیشگی و وفاداری می‌داند، که طی سالیان متمادی و بر پایه اصل اساسی صداقت و درستکاری به دست آورده است.<br>

تیم الورول به واسطه مدیریت گروه بازرگانی آتا امید دارد با عنایت پروردگار بتوانیم رضایت و اعتماد شما هموطنان گرامی را جلب کنیم.

</p>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</main>



{% endblock %}

main/templates/main/contact.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}
    تماس با ما | فروشگاه اینترنتی الورول
{% endblock title %}

{% block content %}


<main class="cart-page default ">
    <div class="container">
        <div class="row">
            <div class="contact_us_content col-12 mx-auto">
                <header class="card-header">
                    <h3 class="card-title"><span>تماس با ما</span></h3>
                </header>
                <div class="account-box contact_us_page">
                
                    <div class="account-box-content">
                            <form action="{% url 'main:contact' %}" method="post" class="form-account">

                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <p class="row">
                                                    <h3>
                                                        <strong>
                                                             آدرس دفتر مرکزی
                                                        </strong>
                                                    </h3>
                                                </p>
                                                <ul>
                                                    <li>
                                                        <i class="fa fa-map  colormain" aria-hidden="true"></i>
خیابان ایرانشهر، کوچه نوشهر، خیابان خردمند جنوبی، پلاک ۲، طبقه ۴، واحد۱۰                                                    </li>
                                                                                         <h3>
                                                        <strong>
                                                             آدرس انبار
                                                        </strong>
                                                    </h3>
                                                    <li>
                                                        <i class="fa fa-map  colormain" aria-hidden="true"></i>
                                                        میدان فردوسی، ابتدای خیابان انقلاب، بن بست شاهرود، پلاک ۱۰، واحد منفی یک
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-envelope colormain" aria-hidden="true"></i> info@aloroll.com
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-phone colormain" aria-hidden="true"></i>
                                                       09102457573 -
{#                                                         ۰۲۱-۵۲۷۱۷#}
                                                        ۰۲۱-۸۷۷۰۰۴۴۷
                                                    </li>
                                                   
                                                </ul>
    
                                                
                                            </div>
                                            


                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-12 form_send_re  ">
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12">
                                            <div class="form-account-title"> نام <span>(الزامی)</span></div>
                                            <div class="form-account-row">
                                                <input class="input_second input_all" id="name" name="name" type="text" placeholder=" نام "required>
                                            </div>
                                        </div>
                      

                                        <div class="col-md-12 col-sm-12">
                                            <div class="form-account-title">ایمیل<span>(الزامی)</span></div>
                                            <div class="form-account-row">
                                                <input class="input_second input_all" id="email" name="email" type="text" placeholder="  ایمیل "required>
                                            </div>
                                        </div>
                                        <div class="col-md-12 col-sm-12">
                                            <div class="form-account-title">تلفن<span>(اختیاری)</span></div>
                                            <div class="form-account-row">
                                                <input class="input_second input_all" id="phone" name="phone" type="number" placeholder="...0912">
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <div class="form-account-title"> موضوع پیام <span>(الزامی)</span></div>
                                            <div class="form-account-row">
                                                <input class="input_second input_all input_textarea text-right" rows="5"  id="subject" name="subject" placeholder=" عنوان پیام را وارد کنید"required></input>
                                            </div>
                                        </div>
                                      
                                        <div class="col-12">
                                            <div class="form-account-title"> متن پیام <span>(الزامی)</span></div>
                                            <div class="form-account-row">
                                                <input class="input_second input_all input_textarea text-right" rows="5"  id="message" name="message" placeholder=" متن درخواست خود را وارد کنید"required></input>
                                            </div>
                                        </div>
                                        <div class="col-12">
{#                                            <div class="form-account-agree">#}
{#                                                <label class="checkbox-form checkbox-primary">#}
{#                                                    <input type="checkbox" id="agree">#}
{#                                                    <span class="checkbox-check"></span>#}
{#                                                </label>#}
{#                                                <label for="agree"> پاسخ به صورت پیامک به من اعلام شود</label>#}
{#                                            </div>#}
                                            <button  class="btn big_btn btn-main-masai" type="submit">ارسال پیام </button>
                                        </div>
 

                                    </div>
                                </div>
                                
                               

                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3239.953298921473!2d51.420028023741004!3d35.7027668287899!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e01d792357689%3A0x509b914bf94bb28!2zYWxvcm9sbCB8INin2YTZiNix2YjZhA!5e0!3m2!1sfa!2s!4v1709733686737!5m2!1sfa!2s"  style="border:0;width:100%;min-height:400px" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


                            </div>


                            {% if success_message %}
                            <div id="success-message" class="alert alert-success">
                                پیام شما با موفقیت ارسال شد!
                            </div>
                            {% endif %}

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

    

{% endblock %}


{% block js %}
<script>
// در تابع form_valid ویو
function showSuccessMessage() {
    var successMessage = document.getElementById('success-message');
    successMessage.style.display = 'block';
}
</script>
{% endblock js %}

main/templates/main/dise.html
{% extends "layouts/base.html" %}

{% load static %}

{% block content %}
    <div class="text-center container bg-white">
    <h1>Roll the Dice!</h1>

    <!-- Link to trigger dice roll using a GET request -->
    <a href="?roll=1"><button>تاس بریز!</button></a>

    {% if roll_value %}
        <div class="dice-result">
            <h2>You rolled: {{ roll_value }}</h2>
        {{ result }}
        </div>
    {% endif %}
</div>
{% endblock %}

main/templates/main/edu.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}
    آموزش خرید | فروشگاه اینترنتی الورول
{% endblock title %}

{% block content %}

<main class="cart-page">

  <div class="container">
    <div class="row">
        <div class="contact_us_content col-12 mx-auto">
            <header class="card-header">
                <h1 style="" class="card-title"><span>
                  گروه بازرگانی آتا
               
                </span>
              </h1>
            </header>
            <div class="account-box contact_us_page">

                <div class="account-box-content text-center">
<video width="600" height="400" controls>
  <source src="{% static 'main/edu.mkv' %}" type="video/mp4">
  مرورگر شما تگ این ویدیو را پشتیبانی نمیکند لطفا از مرورگر دیگری استفاده کنید

</video>
                </div>
            </div>
        </div>
    </div>
</div>

</main>



{% endblock %}